"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.COMPRESSORROOM = void 0;
var mine_drawing_1 = require("./mine_drawing");
var compressorRoom_1 = require("./compressorRoom");
var COMPRESSORROOM = /** @class */ (function (_super) {
    __extends(COMPRESSORROOM, _super);
    // public UndegraundPump1: UndegraundPump;
    function COMPRESSORROOM(container, width, height) {
        var _this = _super.call(this, container, width, height) || this;
        _this.name = 'Compressorroom';
        _this.addBatcher();
        return _this;
    }
    COMPRESSORROOM.prototype.addBatcher = function () {
        this.Pump1 = new compressorRoom_1.Pump(new mine_drawing_1.Point(430, 350), 100, 0);
        this.addWidget(this.Pump1);
        this.Pump1.name = 'Pump1';
        this.Pump2 = new compressorRoom_1.Pump(new mine_drawing_1.Point(612.5, 350), 100, 0);
        this.addWidget(this.Pump2);
        this.Pump1.name = 'Pump2';
        this.Pump3 = new compressorRoom_1.Pump(new mine_drawing_1.Point(795, 350), 100, 0);
        this.addWidget(this.Pump3);
        this.Pump1.name = 'Pump3';
        this.Pump4 = new compressorRoom_1.Pump(new mine_drawing_1.Point(977.5, 350), 100, 0);
        this.addWidget(this.Pump4);
        this.Pump1.name = 'Pump4';
        this.Pump5 = new compressorRoom_1.Pump(new mine_drawing_1.Point(1160, 350), 100, 0);
        this.addWidget(this.Pump5);
        this.Pump1.name = 'Pump5';
        this.Pool1 = new compressorRoom_1.Pool(new mine_drawing_1.Point(400, 550), 900);
        this.addWidget(this.Pool1);
        this.Valve1 = new compressorRoom_1.Valve(new mine_drawing_1.Point(400, 100), 30, 1, 50);
        this.addWidget(this.Valve1);
        this.Valve1.name = 'Y11';
        this.Valve2 = new compressorRoom_1.Valve(new mine_drawing_1.Point(492, 100), 30, 1, 50);
        this.addWidget(this.Valve2);
        this.Valve2.name = 'Y12';
        this.Valve3 = new compressorRoom_1.Valve(new mine_drawing_1.Point(584, 100), 30, 1, 50);
        this.addWidget(this.Valve3);
        this.Valve3.name = 'Y21';
        this.Valve4 = new compressorRoom_1.Valve(new mine_drawing_1.Point(676, 100), 30, 1, 50);
        this.addWidget(this.Valve4);
        this.Valve4.name = 'Y22';
        this.Valve5 = new compressorRoom_1.Valve(new mine_drawing_1.Point(768, 100), 30, 1, 50);
        this.addWidget(this.Valve5);
        this.Valve5.name = 'Y31';
        this.Valve6 = new compressorRoom_1.Valve(new mine_drawing_1.Point(860, 100), 30, 1, 50);
        this.addWidget(this.Valve6);
        this.Valve6.name = 'Y32';
        this.Valve7 = new compressorRoom_1.Valve(new mine_drawing_1.Point(952, 100), 30, 1, 50);
        this.addWidget(this.Valve7);
        this.Valve7.name = 'Y41';
        this.Valve8 = new compressorRoom_1.Valve(new mine_drawing_1.Point(1044, 100), 30, 1, 50);
        this.addWidget(this.Valve8);
        this.Valve8.name = 'Y42';
        this.Valve9 = new compressorRoom_1.Valve(new mine_drawing_1.Point(1136, 100), 30, 1, 50);
        this.addWidget(this.Valve9);
        this.Valve9.name = 'Y51';
        this.Valve10 = new compressorRoom_1.Valve(new mine_drawing_1.Point(1230, 100), 30, 1, 50);
        this.addWidget(this.Valve10);
        this.Valve10.name = 'Y52';
        this.Valve11 = new compressorRoom_1.Valve(new mine_drawing_1.Point(443, 280), 30, 0, 50);
        this.addWidget(this.Valve11);
        this.Valve11.name = 'Y13';
        this.Valve12 = new compressorRoom_1.Valve(new mine_drawing_1.Point(535, 190), 30, 0, 50);
        this.addWidget(this.Valve12);
        this.Valve12.name = 'Y14';
        this.Valve13 = new compressorRoom_1.Valve(new mine_drawing_1.Point(627, 280), 30, 0, 50);
        this.addWidget(this.Valve13);
        this.Valve13.name = 'Y23';
        this.Valve14 = new compressorRoom_1.Valve(new mine_drawing_1.Point(719, 190), 30, 0, 50);
        this.addWidget(this.Valve14);
        this.Valve14.name = 'Y24';
        this.Valve15 = new compressorRoom_1.Valve(new mine_drawing_1.Point(811, 280), 30, 0, 50);
        this.addWidget(this.Valve15);
        this.Valve15.name = 'Y33';
        this.Valve16 = new compressorRoom_1.Valve(new mine_drawing_1.Point(900, 190), 30, 0, 50);
        this.addWidget(this.Valve16);
        this.Valve16.name = 'Y34';
        this.Valve17 = new compressorRoom_1.Valve(new mine_drawing_1.Point(991, 280), 30, 0, 50);
        this.addWidget(this.Valve17);
        this.Valve17.name = 'Y43';
        this.Valve18 = new compressorRoom_1.Valve(new mine_drawing_1.Point(1084, 190), 30, 0, 50);
        this.addWidget(this.Valve18);
        this.Valve18.name = 'Y44';
        this.Valve19 = new compressorRoom_1.Valve(new mine_drawing_1.Point(1173, 280), 30, 0, 50);
        this.addWidget(this.Valve19);
        this.Valve19.name = 'Y53';
        this.Valve20 = new compressorRoom_1.Valve(new mine_drawing_1.Point(1268, 190), 30, 0, 50);
        this.addWidget(this.Valve20);
        this.Valve20.name = 'Y54';
        this.Valve21 = new compressorRoom_1.Valve(new mine_drawing_1.Point(485, 320), 30, 1, 50);
        this.addWidget(this.Valve21);
        this.Valve21.name = 'Y15';
        this.Valve22 = new compressorRoom_1.Valve(new mine_drawing_1.Point(667, 320), 30, 1, 50);
        this.addWidget(this.Valve22);
        this.Valve22.name = 'Y25';
        this.Valve23 = new compressorRoom_1.Valve(new mine_drawing_1.Point(850, 320), 30, 1, 50);
        this.addWidget(this.Valve23);
        this.Valve23.name = 'Y35';
        this.Valve24 = new compressorRoom_1.Valve(new mine_drawing_1.Point(1032, 320), 30, 1, 50);
        this.addWidget(this.Valve24);
        this.Valve24.name = 'Y45';
        this.Valve25 = new compressorRoom_1.Valve(new mine_drawing_1.Point(1215, 320), 30, 1, 50);
        this.addWidget(this.Valve25);
        this.Valve25.name = 'Y55';
        this.ValveCheck1 = new compressorRoom_1.ValveCheck(new mine_drawing_1.Point(443, 190), 30);
        this.addWidget(this.ValveCheck1);
        this.ValveCheck2 = new compressorRoom_1.ValveCheck(new mine_drawing_1.Point(627, 190), 30);
        this.addWidget(this.ValveCheck2);
        this.ValveCheck3 = new compressorRoom_1.ValveCheck(new mine_drawing_1.Point(811, 190), 30);
        this.addWidget(this.ValveCheck3);
        this.ValveCheck4 = new compressorRoom_1.ValveCheck(new mine_drawing_1.Point(991, 190), 30);
        this.addWidget(this.ValveCheck4);
        this.ValveCheck5 = new compressorRoom_1.ValveCheck(new mine_drawing_1.Point(1173, 190), 30);
        this.addWidget(this.ValveCheck5);
        this.ValveCheck6 = new compressorRoom_1.ValveCheck(new mine_drawing_1.Point(440, 480), 30);
        this.addWidget(this.ValveCheck6);
        this.ValveCheck7 = new compressorRoom_1.ValveCheck(new mine_drawing_1.Point(623, 480), 30);
        this.addWidget(this.ValveCheck7);
        this.ValveCheck8 = new compressorRoom_1.ValveCheck(new mine_drawing_1.Point(806, 480), 30);
        this.addWidget(this.ValveCheck8);
        this.ValveCheck9 = new compressorRoom_1.ValveCheck(new mine_drawing_1.Point(987, 480), 30);
        this.addWidget(this.ValveCheck9);
        this.ValveCheck10 = new compressorRoom_1.ValveCheck(new mine_drawing_1.Point(1169, 480), 30);
        this.addWidget(this.ValveCheck10);
        // this.UndegraundPump1 = new UndegraundPump(new Point(800, 300), 100, 0)
        // this.addWidget(this.UndegraundPump1);
    };
    return COMPRESSORROOM;
}(mine_drawing_1.Scheme));
exports.COMPRESSORROOM = COMPRESSORROOM;
//# sourceMappingURL=_compressorRoom.js.map